
    name: Python CI

on: [push, pull_request]  # Triggers on pushes and PRs

jobs:
  test:
    runs-on: ubuntu-latest  # Uses GitHub's Linux runner
    
    steps:
    - uses: actions/checkout@v4  # Checks out your code
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'  # Change to your preferred version
    
    - name: Check Python version
      run: python --version
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
